### ISSUE TITLE
Driver appears to be incompatible with Pi Pico

### ISSUE THREAD

**Issue by tclymer** [sparkfun/Qwiic_I2C_Py#19]
I am rather new to embedded development but have gotten your Qwiic Joystick and SerLCD series working with the Pi Pico. This module appears to be incompatible with the Pi Pico running CircuitPython 8 and newer ways of connecting to I2C (seems to use an older API?) by using the I2CDriver. Are there any plans to update this to the newer ways of facilitating I2C connections that both the joystick and SerLCD seem to use. It would be helpful to have a consistent means of connection to avoid confusion. Thank you.

**Comment by sfe-SparkFro** [comment]
Hi there, apologies for the delay!

I just tested the Qwiic Joystick with the latest version of [CircuitPython for the Pico W](https://circuitpython.org/board/raspberry_pi_pico_w/) (v9.1.1), and everything works fine on my end. Please ensure you have the latest version of the Qwiic_I2C_Py library installed, older versions of this library did use an older API for CircuitPython (eg. I think locking the bus wasn't required before).

Because I'm unable to find any problems, I'm going to close this issue for now. If you're still having trouble, feel free to re-open this issue, but please give more details about exactly what's going wrong. For instance, if you run the first example of the Qwiic Joystick library, are any error messages printed?

Thank you!
