### ISSUE TITLE
Using pHAT on a different I2C bus

### ISSUE THREAD

**Issue by tamugo** [sparkfun/Qwiic_I2C_Py#5]
I'm working on a project where I am making use of a BME680 and IMU 20948 connected to a Raspberry Pi Zero using the Qwiic pHAT v2.0. I also have a battery pack that connects to the RPi the gpio pins. The pins on the battery's distribution board are connected to the first I2C bus, and so I want to make a second I2C bus and have the BME680 and IMU-20948 route through the new bus, but when I do the second bus shows no active addresses. Is there a way to have them go through a new I2C bus?

**Comment by santaimpersonator** [comment]
Since this issue involves the Qwiic pHAT specifically, I am transferring the issue to the [hardware repository for the Qwiic pHAT](https://github.com/sparkfun/Qwiic_Hat_for_Raspberry_Pi/tree/v30).

With that said, the connection for the I2C pins are hardwired to specific pins from the Raspberry Pi (or other SBC); therefore, you can't just assign different pins and expect the hardware to still work.

To do what you are asking, the Qwiic pHAT cannot be used and you would need one of the [Qwiic jumper cables (male or female)](https://www.sparkfun.com/products/17261) to connect your hardware to the specific pins from the Raspberry Pi (or other SBC) that you are trying to use. Additionally, the [`Qwiic_I2C_Py`](https://github.com/sparkfun/Qwiic_I2C_Py) package that the Qwiic python packages are dependent upon utilizes the `smbus2` python package and implements the default I2C bus pins. You would need to [modify the `Qwiic_I2C_Py` package](https://github.com/sparkfun/Qwiic_I2C_Py/blob/master/qwiic_i2c/linux_i2c.py#L57-L71) (probably around here) for your needs, which is outside the scope of our support.

I am closing this issue since it is impossible to address with the specified hardware. Additionally, any code changes are outside the scope of our support.
